#!/usr/bin/env python

# ARandR -- Another XRandR GUI
# Copyright (C) 2008 -- 2011 chrysn <chrysn@fsfe.org>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Display an xrandr command that reproduces the current setup."""

import optparse

import screenlayout.xrandr
import screenlayout.meta

from pipes import quote as shell_quote

p = optparse.OptionParser(description=__doc__, usage="%prog", version=screenlayout.meta.__version__)
p.parse_args()

server = screenlayout.xrandr.Server()
transition = screenlayout.xrandr.Transition(server)
# FIXME: decide where
# screenlayout.widget.main.TransitionWidget._make_transition_nonempty can live
# to be available here
print " ".join(shell_quote(x) for x in ["xrandr"] + transition.serialize())
